django_lvl5/learning_users/basic_app/urls.py
from django.urls import path
from . import views


app_name = "basic_app"
urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('login/', views.user_login, name="login"),
    path('special/', views.special, name="special")
]

django_lvl5/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

django_lvl5/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

django_lvl5/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfileInfo


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

django_lvl5/learning_users/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse

from .forms import UserForm, UserProfileInfoForm

# Create your views here.

def index(request):
    return render(
        request,
        'basic_app/index.html',
        context={},
        )

@login_required
def user_logout(request):
    logout(request)

    return HttpResponseRedirect(reverse('basic_app:index'))


@login_required
def special(request):
    logout(request)

    return HttpResponse('You are logged in!')


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    
    return render(
        request,
        'basic_app/registration.html',
        context = {
            'registered': registered,
            'user_form': user_form,
            'profile_form': profile_form,
                    }
        )


def user_login(request):

    if request.method == "POST":

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect(reverse('basic_app:index'))
            
            else:
                return HttpResponse('Account not active')

        else:
            print('Someone tried to login and failed!')
            print(f'Username {username} and password {password}')
            return HttpResponse('Invalid login details')

    else:
        return render(
            request,
            'basic_app/login.html',
            context={},
        )

django_lvl5/learning_users/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title_block %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse">
            <a class="navbar-brand" href="{% url 'basic_app:index' %}">HOME</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:register' %}">Register</a> </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}


        {% endblock %}
    </div>

</body>
</html>

django_lvl5/learning_users/basic_app/templates/basic_app/index.html
{% extends "learning_users/base.html" %}


{% block title_block %}
INDEX
{% endblock %}

{% block body_block %}

<div class="jumbotron">
    <h1 class="display1">Django level five</h1>
</div>

{% endblock %}

{% for template in  asdfa %}

{% endfor %}


<div class="container">
    
</div>

django_lvl5/learning_users/basic_app/templates/basic_app/login.html
{% extends "learning_users/base.html" %}


{% block body_block %}
    
<div class="jumbotron">

    <h1>Please login here:</h1>

    <form action="{% url 'basic_app:login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>

</div>

{% endblock body_block %}

django_lvl5/learning_users/basic_app/templates/basic_app/registration.html
{% extends "learning_users/base.html" %}
{% load static %}

{% block title_block %}
REGISTRATION
{% endblock %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering</h1>

    {% else %}
        <h1>Register here!</h1>
        <p>Fill out the form:</p>

        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" value="Register">
        </form>

    {% endif %}
</div>

{% endblock %}

django_lvl5/learning_users/templates/learning_users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title_block %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse">
            <a class="navbar-brand" href="{% url 'basic_app:index' %}">HOME</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:register' %}">Register</a> </li>

                
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:logout' %}">Log out</a> </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:login' %}">Log in</a> </li>
                {% endif %}
                    
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block body_block %}


        {% endblock %}
    </div>

</body>
</html>