social_clone/social_project/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views 
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('singup/', views.SignUp.as_view(), name='singup'),
]

social_clone/social_project/posts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

social_clone/social_project/social_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

social_clone/social_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title_block %}
        {% endblock %}
    </title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat" rel="stylesheet">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light techfont custom-navbar">
        <div class="container">
            <div class="collapse navbar-collapse">
                <a class="navbar-brand bigbrand" href="{% url 'home' %}">HOME</a>

                <ul class="navbar navbar-nav navbar-right">
                    {% if user.is_authenticated %}

                        <li class="nav-item"><a class="nav-link" href="{% url 'posts:create' %}">Post</a> </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a> </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'groups:create' %}">Create Group</a> </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a> </li>
                        <li class="nav-item">Hello {{ user.username }}</li>
                    
                    {% else %}

                        <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Log In</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:singup' %}">Sing Up</span></a></li>

                    {% endif %}

                </ul>

            </div>
        </div>
    </nav>

    <div class="container content">
        <div class="row">
            <div class="col-md-8">
                {% block content %}


                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

social_clone/social_project/templates/index.html
{% extends 'base.html' %}


{% block content %}
    <h1>Welcome to Star Social!</h1>    
{% endblock content %}
    

social_clone/social_project/templates/test.html
{% extends 'base.html' %}


{% block content %}
    <h1>You are now logged in.</h1>    
{% endblock content %}
    

social_clone/social_project/templates/thanks.html
{% extends 'base.html' %}


{% block content %}
    <h1>Thanks for visiting, come back soon!</h1>    
{% endblock content %}