social_clone/social_project/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug:slug>', views.SingleGroup.as_view(), name='single'),
    path('join/<slug:slug>', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug:slug>', views.LeaveGroup.as_view(), name='leave'),
]

social_clone/social_project/posts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

social_clone/social_project/social_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

social_clone/social_project/groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()

from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['name']
    

class GroupMember(models.Model):

    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

social_clone/social_project/groups/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.shortcuts import get_object_or_404

from django.urls import reverse
from django.views import generic

from .models import Group, GroupMember
# Create your views here.


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group


class SingleGroup(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except GroupMember.IntegrityError:
            messages.warning(self.request, 'Warning, already a member')
        else:
            messages.success(self.request, 'You are now a member')

        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            )
        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group')

        return super().get(request, *args, **kwargs)

social_clone/social_project/groups/templates/groups/group_base.html
{% extends 'base.html' %}


{% block content %}
    
    <div class="container">
        <div class="row">
            
            {% block pregroup %}{% endblock pregroup %}
            
            {% block group_content %}{% endblock group_content %}

            {% block postgroup %}{% endblock postgroup %}
                
        </div>
    </div>

{% endblock content %}

social_clone/social_project/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}


{% block pregroup %}

<h1>{{ group.name }}</h1>

<h2>Member Count {{ group.members.count }}</h2>

<div class="content">
    
    {% if user in group.members.all %}

        <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
            <span class="glyphicon glyphicon-remove-circle">Leave</span>
        </a>
    
    {% else %}
        <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-default">
            <span class="glyphicon glyphicon-ok-circle">Join</span>
        </a>
    {% endif %}
        
</div>
    
{% endblock pregroup %}
    

{% block group_content %}
    <div class="col-md-8">
        
        {% if group.posts.count == 0 %}

            <h2>No posts in this group yet!</h2>
        
        {% else %}
            
            {% for post in group.posts.all %}
                {% include 'posts/_post.html' %}
            {% endfor %}
                

        {% endif %}
            
    </div>
{% endblock group_content %}
    

social_clone/social_project/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}

{% load bootstrap4 %}


{% block group_content %}
    <h3>Create a new group</h3>

    <form action="{% url 'groups:create' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-large" value="Create">
    </form>

{% endblock group_content %}

social_clone/social_project/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}


{% block pregroup %}

    <div class="col-md-4">

        <div class="content">

            
            {% if user.is_authenticated %}
                <h2>Wolcome back</h2>
                <a href="{% url 'posts:for_user' username=user.username %}">
                    @{{ user.username }}
                </a>
            {% endif %}
            
            <h2>Groups</h2>

            <p>Welcome to the groups page!</p>

        </div>
        
        {% if user.is_authenticated %}

            <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
                <span class="gluphicon glyphicon-plus-sign">Create new group!</span>
            </a>
            
        {% endif %}
            
    </div>
    
{% endblock pregroup %}


{% block group_content %}

    <div class="col-md-8">
        <div class="list-group">
            
            {% for group in object_list %}
                <a class="list-group_item" href="{% url 'groups:single' slug=group.slug %}">
                    <h3 class="list-group-item-heading">
                        {{ group.name }}
                    </h3>
                    <div class="list-group-item-text container-fluid">
                        {{ group.description }}
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <span class="badge">
                                {{ group.members.count }}
                                member{{ group.members.count|pluralize }}
                            </span>
                        </div>
                        <div class="col-md-4">
                            <span class="badge">
                                {{ group.post.count }}
                                member{{ group.post.count|pluralize }}
                            </span>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

{% endblock group_content %}